CREATE TABLE SENSOR_READING 
(
    ID              INTEGER NOT NULL CONSTRAINT PK_SENSOR_READING PRIMARY KEY,
    LOCATION        VARCHAR(25),
    READ_TIME       TIMESTAMP,
    TEMPERATURE     NUMERIC(3,2),
    HUMIDITY        NUMERIC(3,2),
    WEIGHT          NUMERIC(3,2)
);
